In [86]:
from sklearn.datasets import load_iris

In [87]:
X,y = load_iris(return_X_y=True)  ##returns (data,target)

In [88]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [89]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [90]:
###train_test_split
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [91]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((105, 4), (45, 4), (105,), (45,))

In [92]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

In [93]:
gnb.fit(X_train,y_train)

GaussianNB()

In [94]:
y_pred  = gnb.predict(X_test)

In [95]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]


In [96]:
##when we calculated using randomstate=42 we got 1 value predicted wrong 
##but when we use random state 0 wedid not got anything wrong why

In [97]:
import seaborn as sns
df = sns.load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [98]:
X = df.drop('time',axis=1)
y = df.loc[:,'time']

In [102]:
X.dtypes.ca

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
size             int64
dtype: object

In [62]:
y

0      Dinner
1      Dinner
2      Dinner
3      Dinner
4      Dinner
        ...  
239    Dinner
240    Dinner
241    Dinner
242    Dinner
243    Dinner
Name: time, Length: 244, dtype: category
Categories (2, object): ['Lunch', 'Dinner']

In [63]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
encoder.fit_transform(X,y)

<244x366 sparse matrix of type '<class 'numpy.float64'>'
	with 1464 stored elements in Compressed Sparse Row format>

In [66]:
encoded = encoder.fit_transform(X,y)

In [72]:
encoded.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [74]:
df1 = pd.DataFrame(encoded.toarray())

0    1    2    3    4    5    6    7    8    9    ...  356  357  358  \
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0   
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0   
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0   
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0   
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
239  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0   
240  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0   
241  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0   
242  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0   
243  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

     359  360  361  362  363  364  365  
0    0.0  0.0  1.0  0.0  0.0  0.0  0.0  
1    0.0  0.0  0.0  1.0  0.0  0.0  0.0  
2    0.0  0.0  0.0  1.0  0.0  0.0  0.0  
3    0.0  0.0  1.0  0.0  0.0  0.0  0.0  
4    0.0  0.0  0.0  0.0  1.0  0.0  0.0  
..   ...  ...  ...  ...  ...  ...  ...  
239  0.0  0.0  0.0  1.0  0.0  0.0  0.0  
240  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
241  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
242  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
243  1.0  0.0  1.0  0.0  0.0  0.0  0.0  

[244 rows x 366 columns]

In [77]:
# Import necessary libraries
import seaborn as sns
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import accuracy_score

# Load the "tips" dataset from Seaborn
tips = sns.load_dataset("tips")

# Select features and target
X = tips[['total_bill', 'sex', 'smoker', 'day', 'size']]
y = tips['time']

# Perform one-hot encoding on categorical variables
encoder = OneHotEncoder(drop='first', sparse=False)
X_encoded = encoder.fit_transform(X[['sex', 'smoker', 'day']])

# Combine one-hot encoded features with numerical features
X_encoded = pd.DataFrame(X_encoded, columns=encoder.get_feature_names_out(['sex', 'smoker', 'day']))
X = pd.concat([X[['total_bill', 'size']], X_encoded], axis=1)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Naive Bayes classifier (Multinomial Naive Bayes)
nb_classifier = MultinomialNB()
nb_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = nb_classifier.predict(X_test)

# Calculate the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 1.0


/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:808: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [79]:
X

total_bill  size  sex_Male  smoker_Yes  day_Sat  day_Sun  day_Thur
0         16.99     2       0.0         0.0      0.0      1.0       0.0
1         10.34     3       1.0         0.0      0.0      1.0       0.0
2         21.01     3       1.0         0.0      0.0      1.0       0.0
3         23.68     2       1.0         0.0      0.0      1.0       0.0
4         24.59     4       0.0         0.0      0.0      1.0       0.0
..          ...   ...       ...         ...      ...      ...       ...
239       29.03     3       1.0         0.0      1.0      0.0       0.0
240       27.18     2       0.0         1.0      1.0      0.0       0.0
241       22.67     2       1.0         1.0      1.0      0.0       0.0
242       17.82     2       1.0         0.0      1.0      0.0       0.0
243       18.78     2       0.0         0.0      0.0      0.0       1.0

[244 rows x 7 columns]