In [1]:
#sort search and counting functions

In [3]:
import numpy as np

In [25]:
arr = np.array([4,6,5,5,2,2,2,2,1])

In [26]:
np.sort(arr)

array([1, 2, 2, 2, 2, 4, 5, 5, 6])

In [30]:
np.searchsorted(arr,3)

5

In [28]:
arr1 = np.array([0,345,3,321,21,1,2,0,0,0,0,0])

In [29]:
np.count_nonzero(arr1)

6

In [39]:
np.where(arr<5)  #gives indices

(array([0, 4, 5, 6, 7, 8]),)

In [40]:
np.extract(arr > 2,arr)

array([4, 6, 5, 5])

In [41]:
arr.byteswap()

array([288230376151711744, 432345564227567616, 360287970189639680,
       360287970189639680, 144115188075855872, 144115188075855872,
       144115188075855872, 144115188075855872,  72057594037927936])

In [43]:
#numpy copies and views

In [50]:
arr2 = arr1.view()   #same as swallow copy

In [51]:
arr2

array([    0,   345,     3,   321,    21, 10000,     2,     0,     0,
           0,     0,     0])

In [52]:
arr1

array([    0,   345,     3,   321,    21, 10000,     2,     0,     0,
           0,     0,     0])

In [53]:
arr2[5] = 10000

In [54]:
arr2

array([    0,   345,     3,   321,    21, 10000,     2,     0,     0,
           0,     0,     0])

In [55]:
arr1

array([    0,   345,     3,   321,    21, 10000,     2,     0,     0,
           0,     0,     0])

In [63]:
arr3 = arr1.copy ()   #swallow copy

In [64]:
arr3

array([    0,   345,     3,   321,    21, 10000,     2,     0,     0,
           0,     0,     0])

In [65]:
arr3[5] = 99999

In [66]:
arr1

array([    0,   345,     3,   321,    21, 10000,     2,     0,     0,
           0,     0,     0])

In [67]:
arr3

array([    0,   345,     3,   321,    21, 99999,     2,     0,     0,
           0,     0,     0])

In [68]:
#Numpy Matrix library

In [71]:
import numpy.matlib as nm

In [72]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [74]:
nm.ones((3,4),int)

matrix([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [76]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [77]:
#Numpy - Linear Algebra

In [78]:
arr1 = np.random.randint([[2,3],[4,5]])

In [80]:
arr2 = np.random.randint([[5,3],[2,5]])

In [81]:
arr1 @ arr2

array([[ 2,  8],
       [ 8, 16]])

In [84]:
np.dot(arr1,arr2)   #same as arr1 @ arr2

array([[ 2,  8],
       [ 8, 16]])

In [85]:
#search for in built functions for eigen value and eigen vectors 