In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [3]:
ar  = np.array(l)   #1-D array

In [4]:
type(ar)

numpy.ndarray

In [5]:
np.array([[1,2],[3,4]])  #2-D array

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray(l)     #nd array

array([1, 2, 3, 4])

In [8]:
a = [2,3,4,9]
np.asanyarray(a)

array([2, 3, 4, 9])

In [9]:
b = np.matrix(a)

In [10]:
b

matrix([[2, 3, 4, 9]])

In [12]:
np.asanyarray(b)     #if already a form of array the it does not convert to any form of array

matrix([[2, 3, 4, 9]])

In [13]:
b

matrix([[2, 3, 4, 9]])

In [14]:
a


[2, 3, 4, 9]

In [17]:
a = np.array(a)

In [18]:
a

array([2, 3, 4, 9])

In [19]:
c = a

In [20]:
c

array([2, 3, 4, 9])

In [21]:
c[0] 

2

In [22]:
c[0] = 100 

In [23]:
c

array([100,   3,   4,   9])

In [25]:
a    #a also gets changed (swallow copy)

array([100,   3,   4,   9])

In [38]:
d = np.copy(a)   #no connection  (deep copy)

In [39]:
a

array([100, 400,   4,   9])

In [40]:
d

array([100, 400,   4,   9])

In [41]:
a[1] = 400

In [42]:
d

array([100, 400,   4,   9])

In [43]:
a

array([100, 400,   4,   9])

In [45]:
np.fromfunction(lambda i,j : i == j ,(3,3))   #3 x 3 matrix

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [47]:
np.fromfunction(lambda i,j : i*j , (3,3))   #i varies form 0 to 2 also j varies from 0 to 2

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [54]:
iterable = ( i*i for i in range(5))

In [55]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [64]:
np.fromstring('234 567',int,sep = ' ')  #here d type is optional

array([234, 567])

In [65]:
np.fromstring('12,456',sep = ',')

array([ 12., 456.])

In [67]:
#Numpy Data types

In [73]:
l =[2,3,4,5,6]

In [74]:
ar = np.array(l)

In [75]:
ar

array([2, 3, 4, 5, 6])

In [76]:
ar.ndim

1

In [77]:
ar2 = np.array([[1,2,3,4],[5,5,6,7]])

In [78]:
ar2

array([[1, 2, 3, 4],
       [5, 5, 6, 7]])

In [79]:
ar2.ndim

2

In [80]:
ar.size

5

In [81]:
ar2.size

8

In [85]:
ar2.shape #2-D 2rows 4 columns

(2, 4)

In [86]:
ar.shape   #linear 1 row 5 columns

(5,)

In [89]:
ar.dtype

dtype('int64')

In [90]:
ar2.dtype

dtype('int64')

In [96]:
ar22 = np.array([(1.6,2,3,4), (77,88,99,100)]) #any one is float all are converted to float

In [97]:
ar22.dtype

dtype('float64')

In [99]:
list(range(5))

[0, 1, 2, 3, 4]

In [101]:
list(range(5,12))

[5, 6, 7, 8, 9, 10, 11]

In [105]:
list(range(0.1,12))

TypeError: 'float' object cannot be interpreted as an integer

In [107]:
np.arange(2.3,5.6)   #jump is 1 predefined

array([2.3, 3.3, 4.3, 5.3])

In [109]:
np.arange(2.3,5.6,0.3)   #jump is 0.3

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [111]:
list(np.arange(2.3,5.6,0.3))   #jump is 0.3

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [114]:
np.linspace(1,5,10)  #divides 1 to 5 in 10 parts

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [116]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [117]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [118]:
np.zeros((3,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [121]:
np.zeros((2,3,5,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [125]:
 np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [126]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [129]:
 np.ones((2,5,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [130]:
 on = np.ones((2,5,8))

In [131]:
on + 5

array([[[6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6.]]])

In [132]:
on

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [133]:
on *7


array([[[7., 7., 7., 7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7., 7., 7., 7.]],

       [[7., 7., 7., 7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7., 7., 7., 7.]]])

In [140]:
np.empty((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [141]:
np.empty((6,7))

array([[4.68092934e-310, 0.00000000e+000, 6.90807716e-310,
        6.90807906e-310, 6.90807716e-310, 6.90807906e-310,
        6.90807716e-310],
       [6.90807906e-310, 6.90807716e-310, 6.90807906e-310,
        6.90807716e-310, 6.90807906e-310, 6.90807716e-310,
        6.90807906e-310],
       [6.90807716e-310, 6.90807906e-310, 6.90807716e-310,
        6.90807906e-310, 6.90807716e-310, 6.90807906e-310,
        6.90807716e-310],
       [6.90807906e-310, 6.90807716e-310, 6.90807906e-310,
        6.90807716e-310, 6.90807906e-310, 6.90807716e-310,
        6.90807906e-310],
       [6.90807716e-310, 6.90807906e-310, 6.90807716e-310,
        6.90807906e-310, 6.90807716e-310, 3.17095856e+180,
        7.68523957e+170],
       [3.03181447e+180, 4.24510207e+175, 1.09971032e+155,
        2.51119862e+156, 4.73669460e+164, 2.19993640e-152,
        2.02761816e+174]])

In [143]:
np.eye(4)  #identity matrix of dim 4 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [144]:
np.linspace(2,4,10)

array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
       3.11111111, 3.33333333, 3.55555556, 3.77777778, 4.        ])

In [150]:
np.logspace(2,32,5,base = 2)

array([4.00000000e+00, 7.24077344e+02, 1.31072000e+05, 2.37265664e+07,
       4.29496730e+09])

In [155]:
np.random.randn(3,4)

array([[-1.22477463,  0.30851647, -0.44974629, -0.23531846],
       [-0.47232178, -0.50103447, -0.41560306,  0.24206125],
       [-0.78795752, -0.47293078, -0.19226055,  0.27403688]])

In [165]:
arr = np.random.randn(3,4)      #randn function /standard normal distribution mean = 0 ; std = 1

In [166]:
import pandas as pd

In [167]:
pd.DataFrame(arr)

0         1         2         3
0 -1.469975  1.025878  0.912863 -0.052541
1  0.209630 -2.076557  2.810664  0.355203
2 -0.166060  0.303109 -0.512984 -0.453294

In [168]:
np.random.rand(3,4)     #podduces randomly

array([[0.90436318, 0.06197601, 0.99289838, 0.88751673],
       [0.28649067, 0.56559598, 0.25706117, 0.20360101],
       [0.25184863, 0.67387614, 0.76974807, 0.88934568]])

In [169]:
np.random.randint(1,110,(3,5))

array([[ 24,  96,  48,  29,   2],
       [100,   9,   4,   2,  94],
       [ 76,   6,   1, 103,  99]])

In [171]:
pd.DataFrame(np.random.randint(1,110,(3,5)))

0   1   2   3   4
0  12  97  35  38  86
1  61  86  62  23  89
2  40  52  39  76  46

In [172]:
pd.DataFrame(np.random.randint(1,110,(3,5))).to_csv("example.csv")

In [174]:
arr = np.random.rand(3,4)    #3*4 = 12

In [178]:
arr5 = arr.copy

In [179]:
arr

array([[0.01366599, 0.28150861, 0.41929246, 0.76338658],
       [0.35040499, 0.24290328, 0.74415515, 0.25846668],
       [0.35249711, 0.21124388, 0.51070568, 0.15831698]])

In [182]:
arr5 = np.copy(arr)

In [183]:
arr5

array([[0.01366599, 0.28150861, 0.41929246, 0.76338658],
       [0.35040499, 0.24290328, 0.74415515, 0.25846668],
       [0.35249711, 0.21124388, 0.51070568, 0.15831698]])

In [184]:
arr5.reshape(2,6)

array([[0.01366599, 0.28150861, 0.41929246, 0.76338658, 0.35040499,
        0.24290328],
       [0.74415515, 0.25846668, 0.35249711, 0.21124388, 0.51070568,
        0.15831698]])

In [185]:
arr.reshape(6,-12131)

array([[0.01366599, 0.28150861],
       [0.41929246, 0.76338658],
       [0.35040499, 0.24290328],
       [0.74415515, 0.25846668],
       [0.35249711, 0.21124388],
       [0.51070568, 0.15831698]])

In [190]:
arr.reshape(-1515,1)

array([[0.01366599],
       [0.28150861],
       [0.41929246],
       [0.76338658],
       [0.35040499],
       [0.24290328],
       [0.74415515],
       [0.25846668],
       [0.35249711],
       [0.21124388],
       [0.51070568],
       [0.15831698]])

In [193]:
arr1 = arr.reshape(6,-25215)   #any -ve value but not any positive value

In [194]:
arr1

array([[0.01366599, 0.28150861],
       [0.41929246, 0.76338658],
       [0.35040499, 0.24290328],
       [0.74415515, 0.25846668],
       [0.35249711, 0.21124388],
       [0.51070568, 0.15831698]])

In [195]:
arr1

array([[0.01366599, 0.28150861],
       [0.41929246, 0.76338658],
       [0.35040499, 0.24290328],
       [0.74415515, 0.25846668],
       [0.35249711, 0.21124388],
       [0.51070568, 0.15831698]])

In [196]:
arr1[1][1]

0.7633865840936833

In [198]:
arr1[2:5,1]   #row 2 to 4 , 2nd element

array([0.24290328, 0.25846668, 0.21124388])

In [200]:
arr = np.random.randint(1,100,(5,5))

In [201]:
arr

array([[58, 34,  9, 33, 36],
       [92, 38, 70, 98, 60],
       [56, 73, 40, 22, 93],
       [16, 84, 70, 36, 70],
       [76, 28, 27,  4, 97]])

In [207]:
arr3 = arr[arr > 50]

In [208]:
arr3

array([58, 92, 70, 98, 60, 56, 73, 93, 84, 70, 70, 76, 97])

In [209]:
arr >50

array([[ True, False, False, False, False],
       [ True, False,  True,  True,  True],
       [ True,  True, False, False,  True],
       [False,  True,  True, False,  True],
       [ True, False, False, False,  True]])

In [211]:
arr[arr > 50]

array([58, 92, 70, 98, 60, 56, 73, 93, 84, 70, 70, 76, 97])

In [226]:
arr[2:4,[1,2]]

array([[73, 40],
       [84, 70]])

In [216]:
arr

array([[58, 34,  9, 33, 36],
       [92, 38, 70, 98, 60],
       [56, 73, 40, 22, 93],
       [16, 84, 70, 36, 70],
       [76, 28, 27,  4, 97]])

In [227]:
arr5 = [11,22,33,44,55,66]

In [240]:
arr6 = np.array(arr5)

In [236]:
arr6[[1,2]]

array([22, 33])

In [241]:
arr5

[11, 22, 33, 44, 55, 66]

In [242]:
arr6

array([11, 22, 33, 44, 55, 66])

In [251]:
arr6[[3,4,5]]

array([44, 55, 66])

In [252]:
arr1 = np.random.randint(1,3,(3,3))

In [253]:
arr2 =np.random.randint(1,3,(3,3))

In [257]:
arr1


array([[1, 2, 1],
       [2, 1, 1],
       [2, 1, 2]])

In [258]:
arr2

array([[2, 2, 2],
       [2, 2, 2],
       [2, 1, 1]])

In [260]:
arr1 + arr2

array([[3, 4, 3],
       [4, 3, 3],
       [4, 2, 3]])

In [263]:
arr1 * arr2   #same index values multiplictaion simply its not matriox multiolication 

array([[2, 4, 2],
       [4, 2, 2],
       [4, 1, 2]])

In [262]:
arr1 ** arr2

array([[1, 4, 1],
       [4, 1, 1],
       [4, 1, 2]])

In [264]:
arr1 @ arr2    # @ symbol is used for matrix multiplication

array([[ 8,  7,  7],
       [ 8,  7,  7],
       [10,  8,  8]])

In [265]:
arr1 / 0

/tmp/ipykernel_389/824215542.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [266]:
inf is infizity

NameError: name 'inf' is not defined

In [267]:
arr1 


array([[1, 2, 1],
       [2, 1, 1],
       [2, 1, 2]])

In [268]:
arr1 +100

array([[101, 102, 101],
       [102, 101, 101],
       [102, 101, 102]])

In [269]:
arr1 ** arr2

array([[1, 4, 1],
       [4, 1, 1],
       [4, 1, 2]])

In [272]:
arr = np.zeros((4,4))

In [273]:
arr


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [274]:
row = [1,2,3,4]

In [276]:
arr +  row  #row wise braodcasting

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [277]:
row.T

AttributeError: 'list' object has no attribute 'T'

In [291]:
col = np.array([row])    #to make linear row to 2dimensional matrix to take its transpose

In [292]:
col

array([[1, 2, 3, 4]])

In [293]:
col

array([[1, 2, 3, 4]])

In [294]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [295]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [298]:
arr + col.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [299]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [300]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [303]:
arr1 = np.random.randint(1,4,(3,4))

In [304]:
arr1

array([[2, 2, 3, 2],
       [1, 1, 1, 1],
       [2, 1, 1, 2]])

In [305]:
np.sqrt(arr1)

array([[1.41421356, 1.41421356, 1.73205081, 1.41421356],
       [1.        , 1.        , 1.        , 1.        ],
       [1.41421356, 1.        , 1.        , 1.41421356]])

In [306]:
np.exp(arr1)

array([[ 7.3890561 ,  7.3890561 , 20.08553692,  7.3890561 ],
       [ 2.71828183,  2.71828183,  2.71828183,  2.71828183],
       [ 7.3890561 ,  2.71828183,  2.71828183,  7.3890561 ]])

In [308]:
np.log10(arr1)

array([[0.30103   , 0.30103   , 0.47712125, 0.30103   ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.30103   , 0.        , 0.        , 0.30103   ]])