### K Nearest Neighbour Classfier

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline


In [2]:
from sklearn.datasets import make_classification
X , y = make_classification(n_samples=1000,n_features=3,
                            n_redundant=1,
                            n_classes=2,random_state=999)

In [3]:
X

array([[-0.33504974,  0.02852654,  1.16193084],
       [-1.37746253, -0.4058213 ,  0.44359618],
       [-1.04520026, -0.72334759, -3.10470423],
       ...,
       [-0.75602574, -0.51816111, -2.20382324],
       [ 0.56066316, -0.07335845, -2.15660348],
       [-1.87521902, -1.11380394, -4.04620773]])

In [4]:
y

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(
    X,y,random_state=42,test_size=0.33)

In [6]:
from sklearn.neighbors import KNeighborsClassifier

In [7]:
classifier = KNeighborsClassifier()

In [8]:
classifier.fit(X_train,y_train)

KNeighborsClassifier()

In [9]:
y_pred = classifier.predict(X_test)

In [10]:
from sklearn.metrics import (accuracy_score,classification_report,confusion_matrix)

In [11]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[158  11]
 [ 20 141]]
0.906060606060606
              precision    recall  f1-score   support

           0       0.89      0.93      0.91       169
           1       0.93      0.88      0.90       161

    accuracy                           0.91       330
   macro avg       0.91      0.91      0.91       330
weighted avg       0.91      0.91      0.91       330



In [12]:
###Task use grid search CV here and also use for loop

In [13]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
k_params = []

for i in range(10):
    k_params.append(i+1)
    
def foo(X_train,X_test,y_train,y_test,neigh_num):
    
    report = {}
    
    for i in range(neigh_num):
        ##Create classfier
        classifier = KNeighborsClassifier(n_neighbors= (i+1))
        classifier.fit(X_train,y_train)
        y_pred = classifier.predict(X_test)
        score = accuracy_score(y_test,y_pred)
        report[k_params[i]] = score
    
    return report 

In [14]:
report = foo(X_train,X_test,y_train,y_test,10)

In [15]:
values_accu = list(report.values())

In [16]:
max(values_accu)

0.9151515151515152

In [17]:
##Grid search CV

In [97]:
parameters = {'n_neighbors' : k_params ,
             'weights' : ['uniform','distance'] ,
             'p' : [1,2] ,
            'algorithm' : ['ball_tree','kd_tree','auto'],
              'metric': ['minkowski', 'manhattan', 'euclidean']
            }

from sklearn.model_selection import GridSearchCV
clf  = GridSearchCV(KNeighborsClassifier(),param_grid =parameters ,cv =3,scoring = 'accuracy',verbose=3)

In [98]:
clf.fit(X_train,y_train)


Fitting 3 folds for each of 360 candidates, totalling 1080 fits
[CV 1/3] END algorithm=ball_tree, metric=minkowski, n_neighbors=1, p=1, weights=uniform;, score=0.879 total time=   0.0s
[CV 2/3] END algorithm=ball_tree, metric=minkowski, n_neighbors=1, p=1, weights=uniform;, score=0.852 total time=   0.0s
[CV 3/3] END algorithm=ball_tree, metric=minkowski, n_neighbors=1, p=1, weights=uniform;, score=0.874 total time=   0.0s
[CV 1/3] END algorithm=ball_tree, metric=minkowski, n_neighbors=1, p=1, weights=distance;, score=0.879 total time=   0.0s
[CV 2/3] END algorithm=ball_tree, metric=minkowski, n_neighbors=1, p=1, weights=distance;, score=0.852 total time=   0.0s
[CV 3/3] END algorithm=ball_tree, metric=minkowski, n_neighbors=1, p=1, weights=distance;, score=0.874 total time=   0.0s
[CV 1/3] END algorithm=ball_tree, metric=minkowski, n_neighbors=1, p=2, weights=uniform;, score=0.884 total time=   0.0s
[CV 2/3] END algorithm=ball_tree, metric=minkowski, n_neighbors=1, p=2, weights=unifor

GridSearchCV(cv=3, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['ball_tree', 'kd_tree', 'auto'],
                         'metric': ['minkowski', 'manhattan', 'euclidean'],
                         'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                         'p': [1, 2], 'weights': ['uniform', 'distance']},
             scoring='accuracy', verbose=3)

In [99]:
y_pred = clf.predict(X_test)

In [100]:
print(accuracy_score(y_test,y_pred))

0.9181818181818182


In [101]:
clf.best_params_

{'algorithm': 'ball_tree',
 'metric': 'minkowski',
 'n_neighbors': 7,
 'p': 1,
 'weights': 'uniform'}

In [102]:
report

{1: 0.8787878787878788,
 2: 0.8727272727272727,
 3: 0.8878787878787879,
 4: 0.896969696969697,
 5: 0.906060606060606,
 6: 0.896969696969697,
 7: 0.9151515151515152,
 8: 0.9090909090909091,
 9: 0.9121212121212121,
 10: 0.906060606060606}